node:
  agg-switch01:
    mlag:
      address: 169.254.1.1/30
      backupip: 192.168.200.2
      members:
        - swp10
        - swp11
      peerip: 169.254.1.2
      sysmac: "44:38:39:FF:01:56"
      priority: 100
      interfaces:
        bond01:
          clagid: 1
          members: swp1
          mode: access
          vlans:
            - 5
        bond02:
          clagid: 2
          members: swp2
          mode: access
          vlans:
            - 5
        bond03:
          clagid: 3
          members: swp3
          mode: access
          vlans:
            - 5
    routing:
      lo: 10.4.4.1/32
      bgp:
        asn: 65444
        underlay:
          external:
            peers:
              - swp20
          internal:
            peers:
              - swp10
              - swp11
    switching:
      bridge:
        - bond01
        - bond02
        - bond03
        - swp7
      interface:
        swp1:
          mode: bond
          vlan: bond
        swp2:
          mode: bond
          vlan: bond
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
  agg-switch02:
    mlag:
      address: 169.254.1.2/30
      backupip: 192.168.200.1
      members:
        - swp10
        - swp11
      peerip: 169.254.1.1
      sysmac: "44:38:39:FF:01:56"
      priority: 2000
      interfaces:
        bond01:
          clagid: 1
          members: swp1
          mode: access
          vlans:
            - 5
        bond02:
          clagid: 2
          members: swp2
          mode: access
          vlans:
            - 5
        bond03:
          clagid: 3
          members: swp3
          mode: access
          vlans:
            - 5
    switching:
      bridge:
        - bond01
        - bond02
        - bond03
        - swp7
      interface:
        swp1:
          mode: bond
          vlan: bond
        swp2:
          mode: bond
          vlan: bond
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      lo: 10.4.4.2/32
      bgp:
        asn: 65444
        underlay:
          external:
            peers:
              - swp20
          internal:
            peers:
              - swp10
              - swp11
