node:
  closet-switch01:
    bonds:
      bond01:
        members:
          - swp1
      bond02:
        members:
          - swp2
      bond03:
        members:
          - swp3
    switching:
      interface:
        bond01:
          mode: access
          vlan: 5
        bond02:
          mode: access
          vlan: 5
        bond03:
          mode: access
          vlan: 5
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.11/24
          vlan: 5
  closet-switch02:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.22/24
          vlan: 5
  closet-switch03:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.33/24
          vlan: 5
