node:
  closet-switch01:
    switching:
      bonds:
        bond01:
          members:
            - swp1
          mode: access
          vlan: 5
        bond02:
          members:
            - swp2
          mode: access
          vlan: 5
        bond03:
          members:
            - swp3
          mode: access
          vlan: 5
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.11/24
          vlan: 5
  closet-switch02:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.22/24
          vlan: 5
  closet-switch03:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 5
        - 100
    routing:
      svi:
        vlan5:
          ip: 10.5.5.33/24
          vlan: 5
