node:
  wan-rtr:
    routing:
      lo: 10.1.1.1/32
      bgp:
        asn: 65111
        underlay:
          external:
            peers:
              - swp1
              - swp2
          internal:
            peers:
