#####
# Host config for closet-switch-design-l2
#####

- hosts: aggswitches
  become: true
  roles:
  - aggswitches

- hosts: closetswitches
  become: true
  roles:
  - closetswitches

- hosts: wanrtr
  become: true
  roles:
  - wanrtr
